tajulafreen/50Projects-HTML-CSS-JavaScript

HiddenSearch/index.html
HiddenSearch/script.js
HiddenSearch/style.css

**In this PR I made the following changes:**
- No linter errors
- Used ES6
- followed best practices of JavaScript
- followed best practices of HTML and CSS
- create a hidden search bar with the transition and transform

 50Projects-HTML-CSS-JavaScript : Hidden search

---

BluringImage/index.html
BluringImage/script.js
BluringImage/style.css

**In this PR I made the following changes:**
- No linter errors
- Used ES6
- followed best practices of JavaScript
- followed best practices of HTML and CSS
- create a blurry image effect

50Projects-HTML-CSS-JavaScript : Bluring image

---

Source-Code/FormWaveAnimation/index.html
Source-Code/FormWaveAnimation/script.js
Source-Code/FormWaveAnimation/style.css

**In this branch, I made the following changes :**
- No linter errors
- Used ES6
- followed best practices of JavaScript
- followed best practices of HTML and CSS
- Implemented the animation
- use the mouseover effect
- create the glow effect

50Projects-HTML-CSS-JavaScript: Form wave Animation

---

README.md
Source-Code/EventCode/index.html
Source-Code/EventCode/script.js
Source-Code/EventCode/style.css

In this branch, I made the following changes:
- No linter errors
- Used ES6
- followed best practices of JavaScript
- followed best practices of HTML and CSS
- Used event listners
- add functionality
- add readme

50Projects-HTML-CSS-JavaScript: Event code

---

README.md
Source-Code/WeightConverter/index.html
Source-Code/WeightConverter/script.js
Source-Code/WeightConverter/style.css

**Features:**
- Allows users to input weight in kilograms.
- Converts kilograms to grams, pounds, and ounces instantly.
- Responsive design ensures usability across devices.
- Technologies Used: HTML, CSS, JavaScript
**Learning Focus:**
1. DOM manipulation
2. Event handling
3. Responsive web design principles

50Projects-HTML-CSS-JavaScript : Weight converter

---

README.md
Source-Code/AgeCalculator/index.html
Source-Code/AgeCalculator/script.js
Source-Code/AgeCalculator/style.css

**In this branch, I created an Age Calculator project.**
- Structured HTML for better readability and semantics.
- Applied a gradient background and responsive design in CSS.
- Styled the container, input fields, button, and output area for a cohesive look.
- Added a dynamic display of the current date.
- Implemented functionality to calculate and display the user's age based on the input date of birth.
- Enhanced user experience with hover effects on buttons.
- Ensured compatibility and responsiveness across different devices.

50Projects-HTML-CSS-JavaScript : Age calculator

---

README.md
Source-Code/BMICalculator/index.html
Source-Code/BMICalculator/script.js
Source-Code/BMICalculator/style.css

**In this branch, I have created the BMI Calculator:**
- Implemented a BMI Calculator using HTML, CSS, and JavaScript.
- Added input fields for height and weight.
- Developed a calculation function to compute BMI based on user input.
- Displayed the BMI result dynamically on the page.
- Enhanced the user interface for better usability and visual appeal.
- Utilized ES6 syntax for cleaner and more efficient JavaScript code.

50Projects-HTML-CSS-JavaScript : BMI calculator

---

README.md
Source-Code/GradientBackgroundGenerator/index.html
Source-Code/GradientBackgroundGenerator/script.js
Source-Code/GradientBackgroundGenerator/style.css

**In this branch, I have established the project :**
**Summary:**
This pull request adds a Gradient Background Generator to the project. The tool allows users to create custom gradient backgrounds by selecting two colors, viewing the corresponding CSS code, and copying it to the clipboard.
**Features:**
- Added color pickers for selecting two gradient colors.
- Implemented real-time gradient preview as users select colors.
- Displayed the generated CSS code for the gradient background.
- Included a copy button to easily copy the CSS code.
- Styled the tool with responsive design to ensure usability on all devices.
- Enhanced user experience with button animations and transitions.
**Technologies Used:**
- HTML: Structured the web page and form elements.
- CSS: Styled the interface, …

Gradient background generator

---

README.md
Source-Code/Calculator/index.html
Source-Code/Calculator/script.js
Source-Code/Calculator/style.css

**In this branch, I made the following changes :** 
Implemented a basic calculator application using HTML, CSS, and JavaScript.
**Functionality:**
Users can perform basic arithmetic operations including addition, subtraction, multiplication, and division.
- Arithmetic operations are handled using JavaScript functions.
- Includes a clear button to reset the input fields.
- Supports decimal number calculations.
- **Styling:** Added modern styling with CSS to enhance user interface and usability.
- **ES6 Implementation:** Utilized ES6 features for cleaner and more efficient code.

50Projects-HTML-CSS-JavaScript : Calculator

---

README.md
Source-Code/FAQApplication/index.html
Source-Code/FAQApplication/script.js
Source-Code/FAQApplication/style.css

**In this Branch, I made the following changes :** 
- **New Feature:** Introduced a fully functional FAQ Application.
- **Responsive Design:** Ensures optimal viewing and interaction on various devices.
- **Interactive FAQs:** Users can expand and collapse answers with a click.
- **Smooth Animations:** Enhanced with transitions for a better user experience.
- **Customizable CSS:** Allows easy modification of styles for personalization.

50Projects-HTML-CSS-JavaScript : Faq application

---

README.md
Source-Code/ImageFilter/index.html
Source-Code/ImageFilter/script.js
Source-Code/ImageFilter/style.css

**In this branch, I made the following changes :**  
- Added functionality to upload and display images on a canvas.
- Implemented filter adjustments for brightness, contrast, saturation, and vibrance.
- Included artistic effects such as vintage, lomo, clarity, sin city, cross process, pinhole, nostalgia, and her majesty.
- Added buttons for downloading the edited image and reverting to the original image.
- Added styles for components
- Refactored JavaScript code to follow ES6 standards, including the use of let, const, arrow functions, and template literals for better readability and maintainability.

50Projects-HTML-CSS-JavaScript : Image Filter

---

README.md
Source-Code/DayPredictor/index.html
Source-Code/DayPredictor/script.js
Source-Code/DayPredictor/style.css

**In this Branch, I made the following changes :** 
**Added HTML structure:**
- Created a basic HTML file to structure the content.
- Included div elements to display the day of the week and the quote.
**Styled the app with CSS:**
- Designed a simple and clean user interface using CSS.
- Applied styles to enhance the visual appearance of the displayed day and quote.
**Implemented JavaScript functionality:**
- Used ES6 syntax to handle the logic for determining the current day and displaying the appropriate quote.
- Ensured the script runs after the DOM is fully loaded using the DOMContentLoaded event.

50Projects-HTML-CSS-JavaScript : Day predictor

---

README.md
Source-Code/BatteryIndicator/index.html
Source-Code/BatteryIndicator/script.js
Source-Code/BatteryIndicator/style.css

**In this Branch, I made the following changes :** 
- Implemented dynamic battery level display using the Battery Status API.
- Fetched battery level and updated the progress bar width accordingly.
- Displayed the battery percentage as text.
- Added a dark mode toggle functionality.
- Implemented a button to switch between light and dark modes.
- Used CSS class toggling to change the theme.
- Ensured functionality is initialized upon DOM content load for better user experience.
- Improved code readability and maintainability with ES6 syntax and proper event handling.

50Projects-HTML-CSS-JavaScript : Battery indicator

---

README.md
Source-Code/StopWatch/index.html
Source-Code/StopWatch/script.js
Source-Code/StopWatch/style.css

In this Branch, I made the following changes : 
- **Feature Implementation:**
- Created a stopwatch interface using HTML.
- Styled the stopwatch for a clean and modern appearance with CSS.
- Implemented JavaScript functionality to start, stop, and reset the stopwatch.
- Displayed minutes, seconds, and milliseconds for precise time tracking.
- **Enhancements:**
- Ensured the application is responsive and works well on various devices.
- Added event listeners for button interactions (Start, Stop, Reset).
- **index.html:**
- Added the basic structure of the stopwatch interface.
- Included buttons for starting, stopping, and resetting the stopwatch.
- **styles.css:**
- Styled the stopwatch display for a modern look.
- Applied responsive design principles to ensure usability on different …

50Projects-HTML-CSS-JavaScript : Stop watch

---

README.md
Source-Code/JumpGame/index.html
Source-Code/JumpGame/script.js
Source-Code/JumpGame/style.css

**This PR adds the initial implementation of the Jump Game, including :**
- **Basic HTML Structure:** Game layout, character, and blocks.
- **CSS Styling:** Visual design for game elements and animations.
- **JavaScript Logic:** Event handling for character jumps, collision detection, score calculation, and game-over logic.
- **HTML:** Defined game area, character, and blocks.
- **CSS:** Styled game elements and implemented animations for jumping and block movement.
- **JavaScript:** Implemented game logic, including jump function, event listeners, collision detection, and score tracking.

50Projects-HTML-CSS-JavaScript : Jump game

---

README.md
Source-Code/MemoryCard/index.html
Source-Code/MemoryCard/script.js
Source-Code/MemoryCard/style.css

**Features Added:**
- Card Structure: Added HTML and CSS for card layout with front and back faces.
- Card Flip Animation: Implemented CSS animations for flipping cards using 3D transforms.
- Game Logic: Added JavaScript to handle game functionality, including shuffling cards, flipping cards, and checking for matches.
- Game Reset: Implemented a reset button to start a new game.
**Files Changed:**
- index.html: Updated to include card structure with card-front and card-back classes.
- styles.css: Added styles for card flipping animation and card layout.
- script.js: Implemented game logic including card flipping, matching, and resetting.

50Projects-HTML-CSS-JavaScript : Memory card game

---

README.md
Source-Code/ToDoList/index.html
Source-Code/ToDoList/index.js
Source-Code/ToDoList/module/filters.js
Source-Code/ToDoList/module/main.js
Source-Code/ToDoList/style.css

This pull request refactors the To-Do List application by modularizing the JavaScript code into separate modules. The refactoring enhances code organization, readability, and maintainability. The following changes were made:
**main.js:**
- Created functions to handle adding and deleting tasks.
- Exported addTask and deleteTask functions for use in other modules.
**filters.js:**
- Created a function to filter tasks based on the selected category.
- Exported filterTasks function for use in index.js.
**index.js:**
- Imported functions from main.js and filters.js.
- Set up event listeners for adding tasks, filtering tasks, and dynamically handling task deletion.
- Used event delegation to manage delete button clicks.

50Projects-HTML-CSS-JavaScript : To do list

---

README.md
Source-Code/PasswordGenerator/index.html
Source-Code/PasswordGenerator/script.js
Source-Code/PasswordGenerator/style.css

This pull request introduces the Password Generator App, a web-based tool for creating secure passwords. It includes features for selecting password length and character types (uppercase, lowercase, numbers, special characters). The app provides a user-friendly interface and a "copy to clipboard" function for convenience. The code is modular, making future enhancements and maintenance easier.
**Changes Made:**
- Implemented password generation logic based on user-selected criteria.
- Added user interface elements for input selection and password display.
- Integrated copy-to-clipboard functionality for generated passwords.
- Use ES6

50Projects-HTML-CSS-JavaScript : Password generator

---

README.md
Source-Code/NotesKeeper/index.html
Source-Code/NotesKeeper/script.js
Source-Code/NotesKeeper/style.css

**This pull request introduces an updated user interface for the Notes App, enhancing usability, visual appeal, and accessibility. The app allows users to add, display, search, and manage notes through a clean and responsive design. The updated structure focuses on modular code and modern UI components.**
- Use ES6
- Added a responsive navigation bar with a logo, home link, and search form.
- Styled buttons, forms, and containers for better user interaction.
- Local storage integration for persistent note storage.

50Projects-HTML-CSS-JavaScript : Notes keeper

---

README.md
Source-Code/CurrencyConverter/index.html
Source-Code/CurrencyConverter/script.js
Source-Code/CurrencyConverter/style.css

**Description:**
- Created a Currency Converter application using HTML, CSS, and JavaScript.
- Added an input field to enter the amount to be converted.
- Added two dropdown selectors for choosing the source and target currencies.
- Integrated ExchangeRate-API to fetch real-time exchange rates for conversion.
- Implemented a button to trigger the conversion and display the result below the form.
- Styled the app with a simple, clean, and responsive design.
**Changes Made:**
- index.html: Structured the layout with input fields, dropdown selectors, and a button.
- style.css: Added styling to make the app visually appealing and user-friendly.
- script.js: Implemented the JavaScript logic to fetch exchange rates from the API and perform the conversion.

50Projects-HTML-CSS-JavaScript : Currcency converter

---

README.md
Source-Code/RecipeApp/index.html
Source-Code/RecipeApp/script.js
Source-Code/RecipeApp/style.css

**Changes Made:**
- Refactored JavaScript code to use ES6 features:
- Converted functions to arrow functions (searchRecipes and displayRecipes).
- Used template literals for cleaner string interpolation.
- Applied const and let for variable declarations.
- Improved code readability and consistency.
- Enhances code readability and modernizes the codebase.
- Improves maintainability and consistency with modern JavaScript best practices.

50Projects-HTML-CSS-JavaScript : Recipe app

---

README.md
Source-Code/MusicPlayer/index.html
Source-Code/MusicPlayer/script.js
Source-Code/MusicPlayer/style.css

**This PR adds new functionality to the Music Player app, allowing users to:**
- Upload their own songs dynamically via a file input.
- Manage a playlist with real-time updates.
- Navigate the playlist by selecting songs directly.
**Changes Made**
- Updated index.html to include the file upload section and dynamic playlist container.
- Enhanced script.js:
- Added logic for uploading songs and updating the playlist dynamically.
- Modified player functionality to handle custom song inputs.
- Updated styles.css to style the new UI components (e.g., playlist and file input).

50Projects-HTML-CSS-JavaScript : Music player

---

README.md
Source-Code/QuizApp/index.html
Source-Code/QuizApp/script.js
Source-Code/QuizApp/style.css

This is the first implementation of the quiz app built using HTML, CSS, and JavaScript. It allows users to:
- Answer multiple-choice questions.
- Navigate through the quiz with a "Next" button.
- View their score at the end of the quiz.
- Restart the quiz.
- `index.html`: The HTML structure for the quiz app.
- `style.css`: The styling for the quiz interface.
- `script.js`: The JavaScript logic handling quiz questions, answer selection, and scoring.
- Display of multiple-choice questions and answers.
- Handling of answer selection and updating the UI accordingly.
- Score calculation and result display at the end of the quiz.
- Restart button to reset the quiz.

50Projects-HTML-CSS-JavaScript : Quiz app

---

README.md
Source-Code/MemeGenerator/index.html
Source-Code/MemeGenerator/script.js
Source-Code/MemeGenerator/style.css

This is the initial commit of the Meme Generator app, created with HTML, CSS, and JavaScript. The app fetches random memes from the Imgflip API and displays them on the screen. Users can download the current meme image or share it on Twitter.
- `index.html`: The main structure of the Meme Generator app.
- `style.css`: The styling for the app, including layout and button styles.
- `script.js`: The JavaScript logic for fetching memes from the API, displaying them, and handling download and share functionality.
- Fetching random memes from the Imgflip API.
- Displaying the meme image in a responsive layout.
- Adding buttons to download the meme and share it on Twitter.

50Projects-HTML-CSS-JavaScript : Meme generator

---

README.md
Source-Code/TypingSpeedTest/index.html
Source-Code/TypingSpeedTest/script.js
Source-Code/TypingSpeedTest/style.css

This is the initial commit of the Typing Speed Test app created using HTML, CSS, and JavaScript. The app provides a typing test that calculates the user's typing speed in words per minute (WPM) and measures accuracy based on their input compared to a random text.
- **Random Text Selection**: The app displays a random sentence from a predefined list of sample texts for the user to type.
- **Typing Speed Calculation (WPM)**: The app calculates the user's typing speed in words per minute.
- **Accuracy Calculation**: The app calculates the accuracy by comparing the typed text with the randomly selected text.
- **Test Completion**: When the user types the full sentence correctly, the test completes, and an alert is shown with the results.
- **Responsive Design**: The app is designed to be …

50Projects-HTML-CSS-JavaScript : Typing speed test

---

README.md
Source-Code/MovieSearchApp/index.html
Source-Code/MovieSearchApp/script.js
Source-Code/MovieSearchApp/style.css

This pull request introduces a fully functional **Movie Search App** built using HTML, CSS, and JavaScript. The app allows users to search for movies using a public API (OMDB), fetches movie details, and displays them in a responsive layout.
- Search functionality to fetch movies by title.
- Display of movie details, including title, year, and poster.
- Responsive design for improved user experience across devices.
- Error handling for invalid queries or API failures.
1. **index.html**: Structure of the app, including search bar and movie container.
2. **style.css**: Styling for the app's layout and components.
3. **script.js**: JavaScript logic for API integration and dynamic rendering.

50Projects-HTML-CSS-JavaScript : Movie search app

---

README.md
Source-Code/PomodoroTimer/index.html
Source-Code/PomodoroTimer/script.js
Source-Code/PomodoroTimer/style.css

**Description:**
This pull request adds a fully functional Productivity Timer app, allowing users to manage their time effectively with the Pomodoro technique. It includes focus and break intervals, visual animations, and sound notifications to enhance productivity.
**Features Added:**
1. Focus and Break Timer: Alternates between configurable intervals.
2. Dynamic Countdown Display: Real-time updates for session progress.
3. Sound Notifications: Alerts for session transitions.
4. Responsive Design: Works seamlessly on desktop and mobile screens.
**Files Added:**
1. index.html: Markup structure for the app, including timer display and buttons.
2. styles.css: Styling for the layout, animations, and responsiveness.
3. script.js: JavaScript logic for timer functionality and user interactions.

50Projects-HTML-CSS-JavaScript : Pomodoro timer

---

README.md
Source-Code/E-CommerceWebsite/index.html
Source-Code/E-CommerceWebsite/script.js
Source-Code/E-CommerceWebsite/style.css

- Created a simple e-commerce product page displaying products fetched from a public API (`https://fakestoreapi.com/products`).
- Added a "Add to Cart" functionality that allows users to add products to their cart.
- Implemented a modal to view the cart with product names, quantities, and total prices.
- Styled the product list and cart modal for better user experience.
- **Add to Cart**: Users can click "Add to Cart" to add a product to their cart.
- **View Cart**: Clicking the "View Cart" button in the navbar opens a modal displaying the cart items.
- **Cart Items**: Cart shows product name, quantity, and total price for the added products.

50Projects-HTML-CSS-JavaScript : E-commerce website

---

README.md
Source-Code/FoodOrdering/index.html
Source-Code/FoodOrdering/script.js
Source-Code/FoodOrdering/style.css

**Description:** This PR implements the Food Order App with the following features:
- Added a menu with food items: Burger, Pizza, Pasta.
- Each menu item has an Add to Cart button, which adds the item to the cart and updates the total price.
- A cart section displays the items added to the cart along with their prices.
- A Place Order button allows users to confirm their order, which clears the cart after order placement.
- Integrated the functionality using HTML, CSS, and JavaScript.
**Files Changed:**
- index.html: Structure of the page, including the menu and cart section.
- styles.css: Styling for the page, menu items, cart, and buttons.
- script.js: Logic for adding items to the cart, calculating the total price, and placing an order.

50Projects-HTML-CSS-JavaScript : Food ordering app

---

README.md
Source-Code/ChatApp/index.html
Source-Code/ChatApp/script.js
Source-Code/ChatApp/style.css

**Description:**
- Implemented a chat application where users can send messages, and the app echoes the same message as a reply.
- Messages are stored in local storage for persistence across page reloads.
- Designed the UI with distinct styles for user and bot messages.
- Added auto-scroll functionality to display the latest messages.
**Features Added:**
- Message persistence using local storage.
- DOM manipulation for dynamic message display.
- Responsive design for better user experience.
**Preview:**
```
User Message: "Hi"
App Reply: "Hi"
```

50Projects-HTML-CSS-JavaScript : Chat application

---

README.md
Source-Code/InteractivePolling/index.html
Source-Code/InteractivePolling/script.js
Source-Code/InteractivePolling/style.css

This PR introduces an interactive polling app that allows users to vote on a specific color preference. The app tracks votes in real-time, displays the current results, and saves the data in local storage so that the results persist even after the page is refreshed.
- Poll options where users can vote on their favorite color.
- A results section that dynamically updates after each vote.
- Real-time display of the number of votes and percentages for each color.
- Use of local storage to save votes and persist data after page refresh.
- Added `index.html` with the structure of the poll and results section.
- Created `styles.css` to design the polling app interface.
- Developed `script.js` to handle polling logic, including voting functionality, result display, and local storage.

50Projects-HTML-CSS-JavaScript : Interactive polling app

---

README.md
Source-Code/DragAndDrop/index.html
Source-Code/DragAndDrop/script.js
Source-Code/DragAndDrop/style.css

**Description:**
This PR adds a drag-and-drop feature to a simple task list application, where users can move items between two lists. The drag-and-drop functionality is implemented using the native HTML5 Drag and Drop API, and the application is styled using CSS for better user interaction.
**Changes Made:**
- Created two task lists with draggable items inside each list.
- Included basic structure for task list containers.
- Styled the task lists with Flexbox layout to display side-by-side.
- Added hover and dragging effects on list items for better visual feedback.
- Styled lists with a dashed border when an item is dragged over them.
- Implemented the drag-and-drop functionality using event listeners (dragstart, dragend, dragover, dragenter, dragleave, drop).
- Added a class (dragging) …

50Projects-HTML-CSS-JavaScript : Drag and Drop App
